// The Summer Trail range as the product and basket pages read it. The listing
// on index.html carries the same names and prices in its own markup.
window.NORTHMARSH_CATALOGUE = {
  'HR-4182': {
    name: 'Halberd Ridge 45L Pack', price: 168.0, cat: 'Packs', img: 'img/hr-4182.png',
    alt: 'Halberd Ridge 45L Pack in moss green, three-quarter view',
    summary: 'A load-hauling frame pack for three-day routes, built round an alloy perimeter frame that carries the weight on the hips rather than the shoulders.',
    specs: [['Capacity', '45 litres, plus 6 in the floating lid'], ['Weight', '1.62 kg'], ['Back length', 'Adjustable, 44 to 52 cm'], ['Fabric', '210D ripstop body, 420D base'], ['Colours', 'Moss, slate']],
    sizes: ['One size, adjustable back'],
    stock: { 'Quay Lane': 6, 'Thrandle Vale': 3, Duncrieff: 2, 'Wrenfold Mill': 0 },
    ships: true,
  },
  'CP-2290': {
    name: 'Cinderpost Camp Stove', price: 74.5, cat: 'Cook', img: 'img/cp-2290.png',
    alt: 'Cinderpost Camp Stove with folded pot supports',
    summary: 'A wide-burner canister stove with a pre-heat loop, so it keeps a steady simmer in wind and in the cold when a narrow burner would sputter.',
    specs: [['Output', '2.6 kW'], ['Weight', '212 g without canister'], ['Boil time', 'About 4 minutes for a litre, still air'], ['Fuel', 'Screw-thread gas canisters'], ['Packed', 'Folds into a 90 mm pouch']],
    sizes: ['One size'],
    stock: { 'Quay Lane': 11, 'Thrandle Vale': 5, Duncrieff: 4, 'Wrenfold Mill': 2 },
    ships: true,
  },
  'TW-6035': {
    name: 'Thornwick Rain Shell', price: 212.0, cat: 'Layers', img: 'img/tw-6035.png',
    alt: 'Thornwick Rain Shell in slate, hood up',
    summary: 'A three-layer hardshell for days that stay wet, with pit zips for the climb and a wired hood brim that keeps rain off your glasses.',
    specs: [['Fabric', 'Three-layer waterproof membrane, 20,000 mm'], ['Weight', '468 g, size M'], ['Hood', 'Wired brim, helmet compatible'], ['Pockets', 'Two hand, one chest'], ['Seams', 'Fully taped']],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: { 'Quay Lane': 2, 'Thrandle Vale': 0, Duncrieff: 1, 'Wrenfold Mill': 0 },
    ships: false,
  },
  'ML-1174': {
    name: 'Moorlight Trail Lantern', price: 38.0, cat: 'Cook', img: 'img/ml-1174.png',
    alt: 'Moorlight Trail Lantern lit at low output',
    summary: 'A rechargeable camp lantern with a warm low setting that runs for a long evening without flattening the battery.',
    specs: [['Output', '320 lumens on high, 30 on low'], ['Run time', '5 hours high, 40 hours low'], ['Charging', 'USB-C, about 3 hours'], ['Weight', '176 g'], ['Rating', 'Splash resistant']],
    sizes: ['One size'],
    stock: { 'Quay Lane': 14, 'Thrandle Vale': 8, Duncrieff: 6, 'Wrenfold Mill': 3 },
    ships: true,
  },
  'SM-5417': {
    name: 'Saltmarsh Wader Boot', price: 146.0, cat: 'Footwear', img: 'img/sm-5417.png',
    alt: 'Saltmarsh Wader Boot, side profile',
    summary: 'Our own knee-high estuary boot on a lugged block sole, cut wide enough for a thick winter sock and a day on soft mud.',
    specs: [['Height', '38 cm'], ['Upper', 'Natural rubber over a neoprene lining'], ['Sole', 'Lugged block tread'], ['Weight', '1.9 kg the pair, size 9'], ['Fit', 'Wide']],
    sizes: ['UK 5', 'UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11', 'UK 12'],
    stock: { 'Quay Lane': 0, 'Thrandle Vale': 0, Duncrieff: 0, 'Wrenfold Mill': 0 },
    ships: true,
  },
  'GB-5310': {
    name: 'Grimsby Fleece Midlayer', price: 89.0, cat: 'Layers', img: 'img/gb-5310.png',
    alt: 'Grimsby Fleece Midlayer, half-zip',
    summary: 'A grid-back fleece that vents on the climb and traps warmth when you stop, with thumbloop cuffs and a chest stash pocket.',
    specs: [['Fabric', 'Grid-back polyester fleece'], ['Weight', '305 g, size M'], ['Zip', 'Half-length, chin guard'], ['Cuffs', 'Thumbloops'], ['Care', 'Machine wash warm']],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: { 'Quay Lane': 9, 'Thrandle Vale': 6, Duncrieff: 4, 'Wrenfold Mill': 2 },
    ships: true,
  },
  'RG-7726': {
    name: 'Ravensgill Dome Tent', price: 395.0, cat: 'Shelters', img: 'img/rg-7726.png',
    alt: 'Ravensgill Dome Tent pitched on gravel',
    summary: 'A two-person crossed-pole dome that stands up to exposed pitches, with a full-coverage fly and two vestibules for wet kit.',
    specs: [['Sleeps', 'Two'], ['Weight', '2.35 kg packed'], ['Fly', 'Silicone-coated nylon, 3,000 mm'], ['Poles', 'Two crossing alloy poles'], ['Pitch', 'Inner and fly together']],
    sizes: ['Two-person'],
    stock: { 'Quay Lane': 3, 'Thrandle Vale': 2, Duncrieff: 0, 'Wrenfold Mill': 1 },
    ships: false,
  },
  'PT-3049': {
    name: 'Ptarmigan Down Quilt', price: 259.0, cat: 'Sleep', img: 'img/pt-3049.png',
    alt: 'Ptarmigan Down Quilt, partly unrolled',
    summary: 'A sewn-through down quilt for summer nights and bothy floors, with a drawcord footbox and straps that hold it to a sleeping pad.',
    specs: [['Fill', '700-fill responsibly sourced down'], ['Comfort', 'Down to about 5°C'], ['Weight', '640 g, regular'], ['Packed', 'About 4 litres'], ['Lengths', 'Regular, long']],
    sizes: ['Regular', 'Long'],
    stock: { 'Quay Lane': 0, 'Thrandle Vale': 0, Duncrieff: 0, 'Wrenfold Mill': 0 },
    ships: true,
  },
  'QS-5761': {
    name: 'Quarrystone Water Filter', price: 52.0, cat: 'Cook', img: 'img/qs-5761.png',
    alt: 'Quarrystone Water Filter with inline hose',
    summary: 'A hollow-fibre filter that fits inline on a hydration hose or screws onto a bottle, and backflushes with the supplied syringe.',
    specs: [['Rated', '2,000 litres'], ['Pore size', '0.1 micron'], ['Flow', 'About 1 litre a minute'], ['Weight', '85 g'], ['Fits', '28 mm bottle threads and 8 mm hose']],
    sizes: ['One size'],
    stock: { 'Quay Lane': 18, 'Thrandle Vale': 9, Duncrieff: 7, 'Wrenfold Mill': 4 },
    ships: true,
  },
  'AG-2673': {
    name: 'Ashgrove Trekking Poles', price: 96.0, cat: 'Accessories', img: 'img/ag-2673.png',
    alt: 'Ashgrove Trekking Poles, collapsed pair',
    summary: 'Three-section aluminium poles with lever locks you can work in gloves, cork grips, and baskets that swap for mud or snow.',
    specs: [['Length', '105 to 135 cm'], ['Packed', '64 cm'], ['Weight', '520 g the pair'], ['Locks', 'Aluminium lever locks'], ['Grip', 'Cork with foam extension']],
    sizes: ['One size, adjustable'],
    stock: { 'Quay Lane': 7, 'Thrandle Vale': 4, Duncrieff: 3, 'Wrenfold Mill': 1 },
    ships: false,
  },
  'FG-5528': {
    name: 'Fellgate Summit Gloves', price: 64.0, cat: 'Accessories', img: 'img/fg-5528.png',
    alt: 'Fellgate Summit Gloves, palm and back',
    summary: 'A softshell glove for cold ridges, with a goat-leather palm for grip on rock and a soft nose-wipe panel on the thumb.',
    specs: [['Shell', 'Stretch softshell'], ['Palm', 'Goat leather'], ['Lining', 'Brushed fleece'], ['Weight', '96 g the pair, size M'], ['Touchscreen', 'Thumb and forefinger']],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: { 'Quay Lane': 5, 'Thrandle Vale': 3, Duncrieff: 2, 'Wrenfold Mill': 0 },
    ships: true,
  },
  'WN-1806': {
    name: 'Withernsea Dry Bag', price: 29.0, cat: 'Packs', img: 'img/wn-1806.png',
    alt: 'Withernsea Dry Bag, roll-top closed',
    summary: 'A 20-litre roll-top dry bag in coated ripstop, with a purge valve to squeeze out the air before it goes in a pack or a boat.',
    specs: [['Capacity', '20 litres'], ['Fabric', 'PU-coated 70D ripstop'], ['Closure', 'Roll-top with buckle'], ['Valve', 'One-way purge valve'], ['Weight', '110 g']],
    sizes: ['20 litres'],
    stock: { 'Quay Lane': 22, 'Thrandle Vale': 12, Duncrieff: 9, 'Wrenfold Mill': 6 },
    ships: true,
  },
};
